[build]
builder = "NIXPACKS"
buildCommand = "cd app/frontend && rm -rf package-lock.json node_modules && npm install && npm run build && cd ../backend && rm -rf package-lock.json node_modules && npm install"

[deploy]
startCommand = "cd app/backend && node server.js"
restartPolicyType = "ON_FAILURE"

[env]
PORT = "3000"
DB_PATH = "/data/database.sqlite"
